name: Automated Commit Every 5 Minutes

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Make changes to the file
      - name: Modify file
        run: |
          echo "$(date) - Automated commit" >> log.txt

      # Step 3: Commit changes
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add log.txt
          git commit -m "Automated commit at $(date)" || echo "No changes to commit"

      # Step 4: Push changes
      - name: Push changes
        run: |
          git push origin main
