name: Automated Commit Every 6 Hours

on:
  schedule:
    - cron: '0 */6 * * *'  # Trigger every 6 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Pull the latest changes from the remote repository
      - name: Pull latest changes
        run: |
          git pull origin main

      # Step 3: Modify a file (e.g., log.txt)
      - name: Modify file
        run: |
          echo "$(date) - Automated commit triggered" >> log.txt

      # Step 4: Commit changes
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add log.txt
          git commit -m "Automated commit at $(date)" || echo "No changes to commit"

      # Step 5: Push changes to the repository
      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin main
