name: Daily Commit

# Schedule the action to run every 5 minutes
on:
  schedule:
    - cron: "*/5 * * * *" # Every 5 minutes

jobs:
  frequent-commit:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Update the file
      - name: Update file
        run: |
          echo "Commit timestamp: $(date)" >> daily-log.txt

      # Step 3: Commit and push changes
      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add daily-log.txt
          git commit -
